[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@account-abstraction/=lib/account-abstraction/",
    "@openzeppelin/=lib/account-abstraction/node_modules/@openzeppelin/",
]
solc_version = "0.8.28"
evm_version = "cancun"
